### ISSUE TITLE
Instruction on hooking up a system

### ISSUE THREAD

**Issue by mounte** [wherget/ddx3216http#1] opened 2018-04-29 22:06 UTC
Hi,
got hold of one of these mixers and after trying with a cheap usb-midi adapter I can conclude that there are some big differences in how the midi control messages are formed.

For this reason I am curious to hear about your setup and how the mixer was configured. 

I only manage to get midi messages of size 3 bytes. 
On the mixer I am running the 1.11 firmware I believe.
I have the direct par sysex enabled and all of the messages are on format:
( 176,[function/channel],[value] )

And as I mentioned I am running this with a usb to midi adapter connected to my Mac.
Are the 8 bytes due to some other adapter? or some other setting on the mixer?

**Comment by wherget** [comment] 2018-04-30 08:21
The mixer I use and develop this on has firmware 1.12 ("the surround option"), but from the documentation I don't see how that would make much of a difference to the sysex interface (aside from the additional parameters available).

I don't currently have the mixer on hand to check, but if I'm reading the manual right, in the "Rx/Tx" tab of MIDI setup you want "direct par" with black boxes on Rx and Tx, and black boxes on all the parameters. I'll have a check when I get to the mixer again.

The 176-messages you are seeing are regular MIDI control change messages, not sysex. These are expected to only have three bytes, their semantics are documented in the mixer's manual. Since these by design can only have a very coarse control (127 values for the entire fader range), I opted to use the sysex protocol.

Being on a mac and using a generic USB-MIDI interface shouldn't be a problem, that's the setup of my development machine as well. Depending on what software you use to check, sysex messages may not show up without some extra configuration.

Sorry that I can't be of much more help at the moment.

**Comment by mounte** [comment] 2018-05-01 13:08
Hey, no worries about that. Then I believe my setup is very close to yours. Thanks for your input.

**Comment by wherget** [comment] 2018-06-13 12:19
Oh dear, I just found the notification mail in my Inbox, I totally forgot about this. In case it's still any help, here's the settings from my desk:

```
Rx  Tx
[X] [X] Program change
[ ] [ ] Control change
[ ] [X] Machine control
[X] [X] Direct Par Sysex 
```

As expected, `Rx/Tx Only` boxes are all enabled.
Let me know if it worked out for you.

**Comment by wherget** [comment] 2024-07-03 21:02
0.5.0 includes documentation on setup and connections now.  I'm not expecting you to verify this after 6 years, but since it's been working for at least one other person now, I'll be closing this issue and hope it's enough for the moment.

**Closed as completed by wherget** 2024-07-03 21:02 UTC
